// Справочник стран по первым двум символам VIN (ISO 3780 / SAE J853).
// Порядок символов в VIN: A..Z без I, O, Q, затем 1..9, затем 0.
const SEQ = "ABCDEFGHJKLMNPRSTUVWXYZ1234567890";

// Регион по первому символу
const REGIONS = [
  { chars: "ABCDEFGH", name: "Африка" },
  { chars: "JKLMNPR", name: "Азия" },
  { chars: "STUVWXYZ", name: "Европа" },
  { chars: "12345", name: "Северная Америка" },
  { chars: "67", name: "Океания" },
  { chars: "890", name: "Южная Америка" },
];

// [диапазон, страна, ISO-код страны (для флага)]
const COUNTRY_RANGES = [
  // --- Африка ---
  ["AA-AH", "ЮАР", "ZA"],
  ["AJ-AN", "Кот-д’Ивуар", "CI"],
  ["BA-BE", "Ангола", "AO"],
  ["BF-BK", "Кения", "KE"],
  ["BL-BR", "Танзания", "TZ"],
  ["CA-CE", "Бенин", "BJ"],
  ["CF-CK", "Мадагаскар", "MG"],
  ["CL-CR", "Тунис", "TN"],
  ["DA-DE", "Египет", "EG"],
  ["DF-DK", "Марокко", "MA"],
  ["DL-DR", "Замбия", "ZM"],
  ["EA-EE", "Эфиопия", "ET"],
  ["EF-EK", "Мозамбик", "MZ"],
  ["FA-FE", "Гана", "GH"],
  ["FF-FK", "Нигерия", "NG"],
  ["FL-FR", "Мали", "ML"],
  // --- Азия ---
  ["JA-J0", "Япония", "JP"],
  ["KA-KE", "Шри-Ланка", "LK"],
  ["KF-KK", "Израиль", "IL"],
  ["KL-KR", "Южная Корея", "KR"],
  ["KS-K0", "Казахстан", "KZ"],
  ["LA-L0", "Китай", "CN"],
  ["MA-ME", "Индия", "IN"],
  ["MF-MK", "Индонезия", "ID"],
  ["ML-MR", "Таиланд", "TH"],
  ["MS-M0", "Мьянма", "MM"],
  ["NA-NE", "Иран", "IR"],
  ["NF-NK", "Пакистан", "PK"],
  ["NL-NR", "Турция", "TR"],
  ["PA-PE", "Филиппины", "PH"],
  ["PF-PK", "Сингапур", "SG"],
  ["PL-PR", "Малайзия", "MY"],
  ["RA-RE", "ОАЭ", "AE"],
  ["RF-RK", "Тайвань", "TW"],
  ["RL-RR", "Вьетнам", "VN"],
  ["RS-R0", "Саудовская Аравия", "SA"],
  // --- Европа ---
  ["SA-SM", "Великобритания", "GB"],
  ["SN-ST", "Германия", "DE"],
  ["SU-SZ", "Польша", "PL"],
  ["S1-S4", "Латвия", "LV"],
  ["S5-S0", "Великобритания", "GB"],
  ["TA-TH", "Швейцария", "CH"],
  ["TJ-TP", "Чехия", "CZ"],
  ["TR-TV", "Венгрия", "HU"],
  ["TW-T1", "Португалия", "PT"],
  ["UH-UM", "Дания", "DK"],
  ["UN-UT", "Ирландия", "IE"],
  ["UU-UZ", "Румыния", "RO"],
  ["U5-U7", "Словакия", "SK"],
  ["VA-VE", "Австрия", "AT"],
  ["VF-VR", "Франция", "FR"],
  ["VS-VW", "Испания", "ES"],
  ["VX-V2", "Сербия", "RS"],
  ["V3-V5", "Хорватия", "HR"],
  ["V6-V0", "Эстония", "EE"],
  ["WA-W0", "Германия", "DE"],
  ["XA-XE", "Болгария", "BG"],
  ["XF-XK", "Греция", "GR"],
  ["XL-XR", "Нидерланды", "NL"],
  ["XS-XW", "Россия / СССР", "RU"],
  ["XX-X2", "Люксембург", "LU"],
  ["X3-X0", "Россия", "RU"],
  ["YA-YE", "Бельгия", "BE"],
  ["YF-YK", "Финляндия", "FI"],
  ["YL-YR", "Мальта", "MT"],
  ["YS-YW", "Швеция", "SE"],
  ["YX-Y2", "Норвегия", "NO"],
  ["Y3-Y5", "Беларусь", "BY"],
  ["Y6-Y0", "Украина", "UA"],
  ["ZA-ZR", "Италия", "IT"],
  ["ZX-Z2", "Словения", "SI"],
  ["Z3-Z5", "Литва", "LT"],
  ["Z6-Z0", "Россия", "RU"],
  // --- Северная Америка ---
  ["1A-10", "США", "US"],
  ["2A-20", "Канада", "CA"],
  ["3A-3W", "Мексика", "MX"],
  ["3X-37", "Коста-Рика", "CR"],
  ["38-30", "Каймановы острова", "KY"],
  ["4A-40", "США", "US"],
  ["5A-50", "США", "US"],
  // --- Океания ---
  ["6A-6W", "Австралия", "AU"],
  ["7A-7E", "Новая Зеландия", "NZ"],
  // --- Южная Америка ---
  ["8A-8E", "Аргентина", "AR"],
  ["8F-8K", "Чили", "CL"],
  ["8L-8R", "Эквадор", "EC"],
  ["8S-8W", "Перу", "PE"],
  ["8X-82", "Венесуэла", "VE"],
  ["9A-9E", "Бразилия", "BR"],
  ["9F-9K", "Колумбия", "CO"],
  ["9L-9R", "Парагвай", "PY"],
  ["9S-9W", "Уругвай", "UY"],
  ["9X-92", "Тринидад и Тобаго", "TT"],
  ["93-99", "Бразилия", "BR"],
];

// Производитель по WMI (первые 3 символа).
// Вторая строка — фактическая страна завода/подразделения.
const WMI = {
  // --- Германия ---
  WVW: ["Volkswagen (легковые)", "Германия"],
  WV1: ["Volkswagen (коммерческие)", "Германия"],
  WV2: ["Volkswagen (микроавтобусы)", "Германия"],
  WAU: ["Audi", "Германия"],
  WA1: ["Audi (SUV)", "Германия"],
  WUA: ["Audi Sport (quattro GmbH)", "Германия"],
  WBA: ["BMW", "Германия"],
  WBS: ["BMW M", "Германия"],
  WBY: ["BMW i", "Германия"],
  WB1: ["BMW Motorrad", "Германия"],
  WDB: ["Mercedes-Benz", "Германия"],
  WDC: ["Mercedes-Benz (SUV)", "Германия"],
  WDD: ["Mercedes-Benz", "Германия"],
  W1K: ["Mercedes-Benz", "Германия"],
  W1N: ["Mercedes-Benz (SUV)", "Германия"],
  W1V: ["Mercedes-Benz Vans", "Германия"],
  WDA: ["Mercedes-Benz Trucks", "Германия"],
  WMW: ["MINI", "Германия / Великобритания"],
  WME: ["smart", "Германия / Франция"],
  WP0: ["Porsche (легковые)", "Германия"],
  WP1: ["Porsche (SUV)", "Германия"],
  WF0: ["Ford Europe", "Германия"],
  W0L: ["Opel", "Германия"],
  W0V: ["Opel", "Германия"],
  WMA: ["MAN", "Германия"],
  WJM: ["Iveco Magirus", "Германия"],
  // --- Великобритания ---
  SAL: ["Land Rover", "Великобритания"],
  SAJ: ["Jaguar", "Великобритания"],
  SCA: ["Rolls-Royce", "Великобритания"],
  SCB: ["Bentley", "Великобритания"],
  SCC: ["Lotus", "Великобритания"],
  SCE: ["DeLorean", "Великобритания"],
  SCF: ["Aston Martin", "Великобритания"],
  SDB: ["Peugeot UK", "Великобритания"],
  SHS: ["Honda UK", "Великобритания"],
  SJN: ["Nissan UK (Сандерленд)", "Великобритания"],
  SB1: ["Toyota UK (Бернастон)", "Великобритания"],
  // --- Франция / Испания ---
  VF1: ["Renault", "Франция"],
  VF2: ["Renault (LCV)", "Франция"],
  VF3: ["Peugeot", "Франция"],
  VF6: ["Renault Trucks", "Франция"],
  VF7: ["Citroën", "Франция"],
  VF8: ["Matra / Talbot", "Франция"],
  VF9: ["Bugatti", "Франция"],
  VR1: ["DS Automobiles", "Франция"],
  VR3: ["Peugeot", "Франция"],
  VR7: ["Citroën", "Франция"],
  VNK: ["Toyota France (Валансьен)", "Франция"],
  VNE: ["Nissan France", "Франция"],
  VSS: ["SEAT", "Испания"],
  VSE: ["Suzuki Santana", "Испания"],
  VSK: ["Nissan Motor Ibérica", "Испания"],
  VSX: ["Opel España", "Испания"],
  VWV: ["Volkswagen Navarra", "Испания"],
  VX1: ["Renault España", "Испания"],
  // --- Италия ---
  ZFA: ["Fiat", "Италия"],
  ZFC: ["Fiat Veicoli Industriali", "Италия"],
  ZFF: ["Ferrari", "Италия"],
  ZAM: ["Maserati", "Италия"],
  ZAR: ["Alfa Romeo", "Италия"],
  ZHW: ["Lamborghini", "Италия"],
  ZLA: ["Lancia", "Италия"],
  ZCG: ["Cagiva / MV Agusta", "Италия"],
  ZAP: ["Piaggio", "Италия"],
  ZDM: ["Ducati", "Италия"],
  // --- Швеция, Чехия, Венгрия, Словакия, Польша ---
  YV1: ["Volvo (легковые)", "Швеция"],
  YV2: ["Volvo Trucks", "Швеция"],
  YV4: ["Volvo (SUV)", "Швеция"],
  YS2: ["Scania", "Швеция"],
  YS3: ["Saab", "Швеция"],
  TMB: ["Škoda", "Чехия"],
  TMA: ["Hyundai Czech (Ношовице)", "Чехия"],
  TMP: ["Škoda (грузовые)", "Чехия"],
  TRU: ["Audi Hungaria (Дьёр)", "Венгрия"],
  TMK: ["Suzuki Magyar", "Венгрия"],
  TSM: ["Suzuki Magyar", "Венгрия"],
  TM8: ["Kia Slovakia (Жилина)", "Словакия"],
  TMR: ["Kia Slovakia", "Словакия"],
  SUP: ["Opel / FSO", "Польша"],
  SU9: ["Solaris Bus", "Польша"],
  // --- Россия и СНГ ---
  XTA: ["АвтоВАЗ (Lada)", "Россия"],
  XTT: ["УАЗ", "Россия"],
  XTH: ["ГАЗ", "Россия"],
  X96: ["ГАЗ / ПАЗ", "Россия"],
  XUU: ["Автотор (Калининград)", "Россия"],
  XW8: ["Volkswagen Group Rus (Калуга)", "Россия"],
  XWE: ["Hyundai Motor Rus (Санкт-Петербург)", "Россия"],
  XW7: ["Toyota Мотор Мануфэкчуринг Россия", "Россия"],
  X7L: ["Renault Россия (Москва)", "Россия"],
  X7M: ["Hyundai / Kia Россия", "Россия"],
  XMC: ["ПСМА Рус / Mitsubishi (Калуга)", "Россия"],
  Z8N: ["Nissan Мануфэкчуринг Рус (СПб)", "Россия"],
  Z94: ["Hyundai Motor Manufacturing Rus", "Россия"],
  Z6F: ["Ford Sollers (Всеволожск)", "Россия"],
  XWB: ["Uz-Daewoo / Ravon", "Узбекистан"],
  XUF: ["GM Uzbekistan / Chevrolet", "Узбекистан"],
  Y6D: ["ЗАЗ", "Украина"],
  Y7A: ["ЗАЗ / УкрАВТО", "Украина"],
  // --- Япония ---
  JHM: ["Honda", "Япония"],
  JHL: ["Honda (SUV)", "Япония"],
  JH4: ["Acura", "Япония"],
  JH2: ["Honda Motorcycle", "Япония"],
  JT2: ["Toyota (легковые)", "Япония"],
  JT3: ["Toyota (SUV)", "Япония"],
  JTD: ["Toyota", "Япония"],
  JTE: ["Toyota (SUV)", "Япония"],
  JTM: ["Toyota", "Япония"],
  JTN: ["Toyota", "Япония"],
  JTH: ["Lexus", "Япония"],
  JTJ: ["Lexus (SUV)", "Япония"],
  JN1: ["Nissan (легковые)", "Япония"],
  JN6: ["Nissan (коммерческие)", "Япония"],
  JN8: ["Nissan (SUV)", "Япония"],
  JNK: ["Infiniti", "Япония"],
  JF1: ["Subaru", "Япония"],
  JF2: ["Subaru (SUV)", "Япония"],
  JM1: ["Mazda", "Япония"],
  JM3: ["Mazda (SUV)", "Япония"],
  JMZ: ["Mazda", "Япония"],
  JA3: ["Mitsubishi", "Япония"],
  JA4: ["Mitsubishi (SUV)", "Япония"],
  JMB: ["Mitsubishi", "Япония"],
  JMY: ["Mitsubishi", "Япония"],
  JS2: ["Suzuki", "Япония"],
  JS3: ["Suzuki (SUV)", "Япония"],
  JSA: ["Suzuki", "Япония"],
  JDA: ["Daihatsu", "Япония"],
  JYA: ["Yamaha", "Япония"],
  JKA: ["Kawasaki", "Япония"],
  JAL: ["Isuzu", "Япония"],
  JHD: ["Hino", "Япония"],
  // --- Южная Корея ---
  KMH: ["Hyundai", "Южная Корея"],
  KM8: ["Hyundai (SUV)", "Южная Корея"],
  KMF: ["Hyundai (коммерческие)", "Южная Корея"],
  KMJ: ["Hyundai (микроавтобусы)", "Южная Корея"],
  KNA: ["Kia", "Южная Корея"],
  KNB: ["Kia", "Южная Корея"],
  KND: ["Kia (SUV)", "Южная Корея"],
  KNE: ["Kia", "Южная Корея"],
  KNM: ["Renault Samsung", "Южная Корея"],
  KPT: ["SsangYong", "Южная Корея"],
  KPA: ["SsangYong", "Южная Корея"],
  KL1: ["GM Daewoo / Chevrolet", "Южная Корея"],
  KL3: ["GM Korea", "Южная Корея"],
  KL5: ["GM Korea (SUV)", "Южная Корея"],
  KLA: ["Daewoo", "Южная Корея"],
  // --- Китай ---
  LSV: ["SAIC Volkswagen", "Китай"],
  LFV: ["FAW-Volkswagen", "Китай"],
  LVS: ["Changan Ford", "Китай"],
  LVG: ["GAC Toyota", "Китай"],
  LGB: ["Dongfeng Nissan", "Китай"],
  LGW: ["Great Wall / Haval", "Китай"],
  LGX: ["BYD", "Китай"],
  LC0: ["Chery / Omoda", "Китай"],
  LVV: ["Chery", "Китай"],
  LVH: ["Dongfeng Honda", "Китай"],
  LSG: ["SAIC GM", "Китай"],
  LSJ: ["MG / SAIC", "Китай"],
  LB2: ["Geely", "Китай"],
  LB3: ["Geely (Jiangnan)", "Китай"],
  L6T: ["Geely Zhejiang", "Китай"],
  LJD: ["Dongfeng", "Китай"],
  LZW: ["SAIC-GM-Wuling", "Китай"],
  LYV: ["Volvo Китай (Чэнду / Дацин)", "Китай"],
  LRW: ["Tesla Shanghai", "Китай"],
  LNB: ["Exeed / Chery", "Китай"],
  LJ1: ["JAC", "Китай"],
  LPA: ["Changan", "Китай"],
  LS5: ["Changan", "Китай"],
  LMG: ["GAC Trumpchi", "Китай"],
  // --- США / Канада / Мексика ---
  "1G1": ["Chevrolet", "США"],
  "1G6": ["Cadillac", "США"],
  "1GC": ["Chevrolet Truck", "США"],
  "1GM": ["Pontiac", "США"],
  "1GN": ["Chevrolet (SUV)", "США"],
  "1GY": ["Cadillac (SUV)", "США"],
  "1GK": ["GMC (SUV)", "США"],
  "1FA": ["Ford (легковые)", "США"],
  "1FM": ["Ford (SUV)", "США"],
  "1FT": ["Ford Truck", "США"],
  "1FD": ["Ford (грузовые)", "США"],
  "1C3": ["Chrysler", "США"],
  "1C4": ["Chrysler / Jeep", "США"],
  "1C6": ["RAM", "США"],
  "1J4": ["Jeep", "США"],
  "1N4": ["Nissan USA", "США"],
  "1HG": ["Honda USA", "США"],
  "1HD": ["Harley-Davidson", "США"],
  "1ME": ["Mercury", "США"],
  "1LN": ["Lincoln", "США"],
  "1VW": ["Volkswagen USA (Чаттануга)", "США"],
  "1YV": ["Mazda USA", "США"],
  "19U": ["Acura USA", "США"],
  "19X": ["Honda USA", "США"],
  "2G1": ["Chevrolet Канада", "Канада"],
  "2HG": ["Honda Канада", "Канада"],
  "2HK": ["Honda Канада (SUV)", "Канада"],
  "2T1": ["Toyota Канада", "Канада"],
  "2C3": ["Chrysler Канада", "Канада"],
  "2FA": ["Ford Канада", "Канада"],
  "2LM": ["Lincoln Канада", "Канада"],
  "3VW": ["Volkswagen Мексика (Пуэбла)", "Мексика"],
  "3FA": ["Ford Мексика", "Мексика"],
  "3GN": ["Chevrolet Мексика", "Мексика"],
  "3N1": ["Nissan Мексика", "Мексика"],
  "3C4": ["Chrysler Мексика", "Мексика"],
  "3KP": ["Kia Мексика", "Мексика"],
  "3MZ": ["Mazda Мексика", "Мексика"],
  "4S3": ["Subaru USA (Индиана)", "США"],
  "4S4": ["Subaru USA (SUV)", "США"],
  "4T1": ["Toyota USA (Джорджтаун)", "США"],
  "4US": ["BMW USA", "США"],
  "4JG": ["Mercedes-Benz USA (Алабама)", "США"],
  "4M2": ["Mercury (SUV)", "США"],
  "5YJ": ["Tesla (Фримонт)", "США"],
  "7SA": ["Tesla (Остин)", "США"],
  "5NP": ["Hyundai USA (Алабама)", "США"],
  "5XY": ["Kia USA (Джорджия)", "США"],
  "5TD": ["Toyota USA", "США"],
  "5FN": ["Honda USA (SUV)", "США"],
  "5J6": ["Honda USA", "США"],
  "5UX": ["BMW USA (Спартанберг)", "США"],
  "5N1": ["Nissan USA (SUV)", "США"],
  "5LM": ["Lincoln (SUV)", "США"],
  // --- Южная Америка, Индия, Азия, Африка, Океания ---
  "9BW": ["Volkswagen Бразилия", "Бразилия"],
  "9BD": ["Fiat Бразилия", "Бразилия"],
  "9BF": ["Ford Бразилия", "Бразилия"],
  "9BG": ["Chevrolet Бразилия", "Бразилия"],
  "93Y": ["Renault Бразилия", "Бразилия"],
  "93H": ["Honda Бразилия", "Бразилия"],
  "8AP": ["Fiat Аргентина", "Аргентина"],
  "8AF": ["Ford Аргентина", "Аргентина"],
  "8AG": ["Chevrolet Аргентина", "Аргентина"],
  MAT: ["Tata Motors", "Индия"],
  MA1: ["Mahindra", "Индия"],
  MA3: ["Maruti Suzuki", "Индия"],
  MA6: ["GM Индия", "Индия"],
  MAL: ["Hyundai Индия", "Индия"],
  MBH: ["Suzuki Индия", "Индия"],
  MEE: ["Renault Индия", "Индия"],
  MZB: ["Mazda Таиланд", "Таиланд"],
  MMT: ["Mitsubishi Таиланд", "Таиланд"],
  MM8: ["Mazda Таиланд", "Таиланд"],
  MR0: ["Toyota Таиланд", "Таиланд"],
  MR2: ["Toyota Таиланд", "Таиланд"],
  MNT: ["Nissan Таиланд", "Таиланд"],
  MPA: ["Isuzu Таиланд", "Таиланд"],
  MHR: ["Honda Индонезия", "Индонезия"],
  MHF: ["Toyota Индонезия", "Индонезия"],
  NMT: ["Toyota Турция", "Турция"],
  NM0: ["Ford Otosan", "Турция"],
  NLH: ["Hyundai Assan", "Турция"],
  NLE: ["Mercedes-Benz Türk", "Турция"],
  NLA: ["Honda Турция", "Турция"],
  PL1: ["Proton", "Малайзия"],
  PM2: ["Perodua", "Малайзия"],
  RLM: ["Mercedes-Benz Вьетнам", "Вьетнам"],
  RL4: ["VinFast", "Вьетнам"],
  "6F4": ["Ford Австралия", "Австралия"],
  "6G1": ["Holden", "Австралия"],
  "6H8": ["Holden", "Австралия"],
  "6T1": ["Toyota Австралия", "Австралия"],
  AAV: ["Volkswagen ЮАР", "ЮАР"],
  ADD: ["Toyota ЮАР", "ЮАР"],
  AHT: ["Toyota ЮАР", "ЮАР"],
  AFA: ["Ford ЮАР", "ЮАР"],
  AC5: ["Hyundai ЮАР", "ЮАР"],
};
